config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'tasks#index'
  
  # Sessions
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  
  resources :tasks
  resources :users, only: [:show, :create, :edit, :update, :destroy]
  # users#index, showは必要ない・・・
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/m01_status.rb
class M01Status < ApplicationRecord
end

app/models/task.rb
class Task < ApplicationRecord
  # user:Task = 1:多（主従）の関係
  belongs_to :user
  
  # user_idを必須入力にして、userとのヒモ付なしでは保存できないようにする。
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 255 }
  
  # statusカラムの追加によるバリデーションの追加
  validates :status, presence: true, length: { maximum: 10 }
  
end

app/models/user.rb
class User < ApplicationRecord
  # 保存前に、emailの文字列を大文字から小文字に自動変換する
  before_save { self.email.downcase! }
  
  validates :name, presence: true, length: { maximum: 50 }
  validates :age, presence: false, length: { maximum: 3 }
  validates :email, presence: true, length: { maximum: 255 },
            format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
            uniqueness: { case_sensitive: false }
  
  # パスワード用のRailsの標準機能
  has_secure_password
  
  has_many :tasks
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  include SessionsHelper
 
  private 
  
  # ログインしてない場合はlogin_urlにリダイレクトする
  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
  
  def counts(user)
    @count_tasks = user.tasks.count
  end
  
  # Strong Parameter
  def task_params
    params.require(:task).permit(:content, :status)
  end
  
end

app/controllers/sessions_controller.rb
# ■変更内容の説明
# (1) routeの設定を変更したため、redirect先を変更
#
class SessionsController < ApplicationController
  def new
    
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    
    # セッションから取得したemailとpasswordでログインできた場合
    if login(email, password)
      flash[:success] = 'ログインに成功しました'
      @user = current_user
      
      # Edited on 2017/06/29 (1) <<
      # redirect_to @user
      redirect_to tasks_path
      
      # Edited on 2017/06/29 (1) >>
      
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render 'new'
    end
  end

  # ログアウトするとトッフページにリダイレクトする
  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました'
    redirect_to root_path
  end
  
  private
  
  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      # ログインに成功
      session[:user_id] = @user.id
      return true
    else
      # ログイン失敗
      return false
    end
  end
  

  
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  # Added on 2017/06/12 -- 共通化処理 (before_action) <
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:destroy]
  # Added on 2017/06/12 -- 共通化処理 (before_action) >
  
  def index
    # Taskﾃｰﾌﾞﾙの全てのﾚｺｰﾄﾞを@taskｲﾝｽﾀﾝｽ変数に設定
    # View側で、この変数を利用して画面にﾃﾞｰﾀを表示する
    # @tasks = Task.all
    # if logged_in?
    if logged_in?
      @tasks = current_user.tasks.page(params[:page])
      @user = current_user
      
    else
      # @taks = nil
    end
  end
  
  def show
    # 画面から渡されたIDをパラメータとしてデータベースから
    # 該当するレコードを抽出し
    # @task
    
    # 2. Edited on 2017/06/12 -- before_action に変更 <<<
    # 1. Edited on 2017/06/12 -- 共通化処理に変更 <<
    # @task = Task.find(params[:id]) #1
    # set_task #2
    
    # Edited on 2017/06/12 -- 共通化処理に変更 >>
    # Edited on 2017/06/12 -- before_action に変更 >>>
    
  end
  
  def new
    # @task = current_user.Task.new(content: '', status: '')
    # @task = current_user.tasks.new(content: '', status: '')
    @task = current_user.tasks.build(content: '', status: '')
    @user = current_user
    
  end
  
  def create
    
    # @task = Task.new(task_params)
    @task = current_user.tasks.build(task_params)
    
    if @task.save
      flash[:success] = 'Taskが正常に登録されました'
      redirect_to @task
    else
      flash.now[:danger] = 'Taskが登録されませんでした'
      render :new
    end
    
  end
  
  def edit
    # 2. Edited on 2017/06/12 -- before_action に変更 <<<
    # 1. Edited on 2017/06/12 -- 共通化処理に変更 <<
    # @task = Task.find(params[:id]) #1
    # set_task #2
    
    # Edited on 2017/06/12 -- 共通化処理に変更 >>
    # Edited on 2017/06/12 -- before_action に変更 >>>
    
  end
  
  def update
    # 2. Edited on 2017/06/12 -- before_action に変更 <<<
    # 1. Edited on 2017/06/12 -- 共通化処理に変更 <<
    # @task = Task.find(params[:id]) #1
    # set_task #2
    # Edited on 2017/06/12 -- 共通化処理に変更 >>
    # Edited on 2017/06/12 -- before_action に変更 >>>
    
    if @task.update(task_params)
      flash[:success] = 'Taskは正常に更新されました'
      redirect_to @task
    else
      flash.now[:danger] = 'Taskは更新されませんでした'
      render :edit
    end
  end
  
  def destroy
    # 2. Edited on 2017/06/12 -- before_action に変更 <<<
    # 1. Edited on 2017/06/12 -- 共通化処理に変更 <<
    # @task = Task.find(params[:id]) #1
    # set_task #2
    # Edited on 2017/06/12 -- 共通化処理に変更 >>
    # Edited on 2017/06/12 -- before_action に変更 >>>
    
    @task.destroy
    
    flash[:success] = 'Taskは正常に削除されました'
    redirect_to root_path
    
  end
  
  private
  
  def set_task
    # @task = current_user.tasks.find(params[:id])
    @task = current_user.tasks.find_by_id(params[:id])
    
    if @task == nil
      redirect_to root_url
    end
  end
  
  # Strong Parameter
  def task_params
    # Edit, 2017/06/12 - カラム「status」の追加によるパラメータからのstatus取得の追加 <<>>
    params.require(:task).permit(:content, :status)
    # params.require(:m01_status).permit(:m01_status)
  end
  
  def correct_user
    @task = current_user.tasks.find_by(id: params[:id])
    unless @task
      redirect_to root_url
    end
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:index, :show, :edit, :update, :destroy]
  before_action :allow_only_the_user, only: [:edit, :update, :destroy]
  
  
  def index
    # @users = User.all.page(params[:page])
  end

  def show
    if logged_in?
      @user = User.find(params[:id])
      @tasks = @user.tasks.order('created_at DESC').page(params[:page])
    
      counts(@user)
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
      flash[:success] = 'ユーザを登録しました'
      redirect_to @user
    else
      flash.now[:danger] = 'ユーザ登録に失敗しました'
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
    
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    
    #セッション情報を削除
    session[:user_id] = nil
    
    flash[:success] = 'ユーザは正常に削除されました'
    redirect_to root_url
    
  end

  def update
    @user = User.find(params[:id])
    
    if @user.update(user_params)
      flash[:success] = 'ユーザは正常に更新されました'
      redirect_to @user
    else
      flash.now[:danger] = 'ユーザは更新されませんでした'
      render :edit
    end
  end
  
  private
  
  # ユーザパラメータ取得処理
  def user_params
    params.require(:user).permit(:name, :email, :age, :password, :password_confirmation)
  end
  
  # ログインユーザ以外は、不正なアクセスにする
  def allow_only_the_user
    @user = User.find(params[:id])
    
    unless @user == current_user
      flash[:danger] = '不正なアクセスです'
      redirect_to root_url
    end
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  @current_user
  
  def current_user
    # @current_user に既に現在のログインユーザが代入されていたら何もせず、
    # 代入されていなかったら User.find(...) からログインユーザを取得し、
    # @current_user に代入する処理を1行で書いたもの
    
    @current_user ||= User.find_by(id: session[:user_id])
    
  end
  
  
  def logged_in?
    !!current_user
    
  end

  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <!-- Edited on 2017/06/18 for the 2nd kadai of adding Bootstrap (start) -->
  <!--<div><%= message %></div>-->
  <div class="alert alert-<%= message_type %>"><%= message %></div>
  <!-- Edited on 2017/06/18 for the 2nd kadai of adding Bootstrap (end) -->
<% end %>

app/views/layouts/_navbar.html.erb
<header>
  <nav class="navbar navbar-inverse navbar-static-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapsed" 
          data-target="#bs-example-navbar-collapse-1" aria-explanded="false">
          <span class="fr-onlly">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">KadaiTasklist</a>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <% if logged_in? %>
            <li><%= link_to '新規タスクの登録', new_task_path %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" 
                  aria-haspopup="true" aria-expanded="false"><%= current_user.name %><span class="caret"></span></a>
              
              <ul class="dropdown-menu">
                <li><%= link_to 'プロフィールの参照', user_path(current_user)  %></li>
                <li><%= link_to 'プロフィールの編集', edit_user_path(current_user) %></li>
                <li><%= link_to '退会', current_user, method: :delete, 
                  data: { confirm: '本当に退会しますか？' } %></li>
                <li><%= link_to 'Logout', logout_path, method: :delete %></li>
              </ul>
            </li>
            
          <% else %>
            <li><%= link_to 'Sign up now!', signup_path, class: 'btn btn-lg btn-primary' %></li>
            <li><%= link_to 'Login', login_path, class: 'btn btn-lg btn-primary' %></li>
          <% end %>
        </ul>
        
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <title>KadaiTasklist</title>
    <%= csrf_meta_tags %>
    
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <style>
      .center {
        text-align: center;
      }
    </style>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container">
  
      <%= render 'layouts/flash_messages' %>
      
      <%= yield %>
      
    </div>
      
  </body>
</html>

app/views/tasks/_form.html.erb
<div class="row">
  <div class="col-xs-12 col-sm-offset-2 col-md-offset-2 col-sm-8 col-md-8 col-lg-offset-3 col-lg-6">
    <!-- Form_forに対してCSSクラスを設定する場合、htmlオプションとして指定することができる -->
    
    <%= form_for(task) do |f| %>
      <% if task.errors.any? %>
        <!-- edited on 2017/06/18 for adding Bootstrap (start) -->
        <!--<div id="error_explanation">-->
        <div class="alert alert-warning">
        <!-- End of Edit -->
          <ul>
            <% task.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <!-- Edited on 2017/06/18 (Bootcampの追加処理) (start) -->
      <!--<%= f.label :content, 'タスク' %>-->
      <!--<%= f.text_field :content %>-->
      
      <!--<%= f.label :status, 'ステータス' %>-->
      <!--<%= f.text_field :status %>-->
      <!--<%= f.submit '登録' %>-->
      <!-- The above is changed as follows; -->
      
      <div class="form-group">
        <%= f.label :content, 'タスク' %>
        <%= f.text_field :content, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :status, 'ステータス' %>
        <%= f.text_field :status, class: 'form-control' %>
      </div>
      
      <%= f.submit '登録', class: 'btn btn-primary' %>
    
      <!-- Edited on 2017/06/18 (Bootcampの追加処理) (end) -->
    <% end %>
  </div>
</div>

app/views/tasks/edit.html.erb
<span class="center"><h1>id: <%= @task.id %> のタスク編集ページ</h1></span>

<%= render 'form', task: @task %>

app/views/tasks/index.html.erb
<h1>タスク一覧</h1>

 <% if logged_in? %>
  <% if @tasks.any? %>
    <table class="table table-striped">
      <thead>
        <tr>
          <th>id</th>
          <th>タスク</th>
          <th>ステータス</th>
        </tr>
      </thead>
      <tbody>
        <% @tasks.each do |task| %>
          <tr>
            <td><%= link_to task.id, task %></td>
            <td><%= task.content %></td>
            <td><%= task.status %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <div>
      <%= paginate @tasks %>
    </div>
  <% end %>
  
  <%= link_to '新規タスクの登録', new_task_path, class: "btn btn-primary" %>
  
<% else %>
  <%= link_to 'Log in', login_path, class: "btn btn-primary" %>
  
  <%= link_to 'sign up!', signup_path, class: "btn btn-primary" %>
<% end %>

app/views/tasks/new.html.erb
<span class="center"><h1>タスク新規作成ページ</h1></span>

<!-- Edited on 2017/06/12 - 共通化 開始 -->
<!--<%= form_for(@task) do |f| %>-->
<!--  <%= f.label :content, 'タスク' %>-->
<!--  <%= f.text_field :content, placeholder: 'タスクを入力してください' %>-->

<!--  <%= f.submit '登録' %>-->
  
<!--<% end %>-->

<%= render 'form', task: @task %>

<!-- Edited on 2017/06/12 - 共通化 終了 -->

<!--<%= link_to '一覧に戻る', tasks_path %>-->

app/views/tasks/show.html.erb
<!--<h1>id = <%= @task.id %> のタスク詳細ページ</h1>-->

<!-- Edited on 2017/06/18 for adding Bootstrap for kadai of Lesson10 (start) -->
<!--<p>タスク：<%= @task.content %></p>-->
<!--<p>ステータス：<%= @task.status %></p><br>-->
<!--<%= link_to '一覧に戻る', tasks_path %>-->
<!--<%= link_to 'このタスクを編集する', edit_task_path(@task) %>-->
<!--<%= link_to 'このタスクを削除する', @task, method: :delete, data: { confirm: '本当に削除してよろしいですか？'} %>-->

<!-- Changed as follows... -->
<h1>id = <%= @task.id %> のタスク詳細ページ</h1>

<table class="table table-bordered">
  <tr>
    <th>id</th>
    <td><%= @task.id %></td>
  </tr>
  <tr>
    <th>タスク</th>
    <td><%= @task.content %></td>
  </tr>
  <tr>
    <th>ステータス</th>
    <td><%= @task.status %></td>
  </tr>
</table>

<!--<%= link_to '一覧に戻る', tasks_path, class: 'btn-default' %>-->
<%= link_to 'このタスクを編集する', edit_task_path(@task), class: 'btn btn-default' %>
<%= link_to 'このメッセージを削除する', @task, method: :delete, data: { 
  confirm: '本当にこのタスクを削除してもよろしいですか?' }, class: 'btn btn-danger' %>


<!-- Edited on 2017/06/18 for adding Bootstrap for kadai of Lesson10 (start) -->

app/views/users/_users.html.erb
<% if users.any? %>
  <ul class="media-list">
    <% users.each do |user| %>
      <div class="media-body">
        <div>
          id: <%= user.id %>,&nbsp;
        </div>
        <div>
          <%= user.name %>
        </div>
        <div>
          <p><%= link_to 'View profile', user_path(user) %></p>
        </div>
      </div>
    <% end %>
    
  </ul>
  <%= paginate users %>
  
<% end %>

app/views/users/edit.html.erb
<div class="text-center">
  <h1>id:<%= @user.id %>、ユーザ名"<%= @user.name %>"のユーザ情報の編集画面</h1>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
    
      <div class="form-group">
        <%= f.label :name, 'Name' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= f.label :email, 'Email' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= f.label :password, 'Password' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>
    
      <div class="form-group">
        <%= f.label :password_confirmation, 'Confirmation' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= f.label :age, '年齢' %>
        <%= f.text_field :age, class: 'form-control' %>
      </div>
      
      
      <%= f.submit 'Update Your Profile', class: 'btn btn-primary btn-block', data: { confirm: "ユーザ情報を更新してもよろしいですか?"} %>
    <% end %>      
  </div>
  
</div>

app/views/users/new.html.erb
<div class="text-center">
  <h1>Sign up</h1>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    
    <%= form_for(@user) do |f| %>
      <!--エラーメッセージをレンダリング表示する, objectは@userが入る-->
      <%= render 'layouts/error_messages', model: f.object %>
      
      <div class="form-group">
        <%= f.label :name, '名前' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= f.label :email, 'Email' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= f.label :age, '年齢' %>
        <%= f.text_field :age, class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= f.label :password, 'Password' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= f.label :password_confirmation, 'Confirmation' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>
      
      <%= f.submit 'Sign up', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
    <table class="table table-bordered">
      <tr><th style="background-color: #faf1e2;">ID</td><td><%= @user.id %></td></tr>
      <tr><th style="background-color: #faf1e2;">名前</th><td><%= @user.name %></td></tr>
      <tr><th style="background-color: #faf1e2;">Email</th><td><%= @user.email %></td></tr>
      <tr><th style="background-color: #faf1e2;">タスク数</th><td><%= link_to tasks_path do %>Tasks <span class="badge"><%= @count_tasks %></span><% end %></td></tr>
    </table>
  
<%= link_to '戻る', tasks_path, class: "btn btn-default col-xs-2" %>
    <% if @user == current_user %>
      <%= link_to '編集する', edit_user_path(@user), class: "btn btn-primary col-xs-2" %>
      <%= link_to '削除する', @user, method: :delete, class: "btn btn-danger col-xs-2", data: { confirm: '本当に退会しますか？' } %>
    <% end %>
</div>